language: php

php:
    - 7.3

env:
    - SYMFONY_VERSION=4.4.*
    - SYMFONY_VERSION=5.0.*

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - |
        composer require \
            symfony/config:${SYMFONY_VERSION} \
            symfony/dependency-injection:${SYMFONY_VERSION} \
            symfony/framework-bundle:${SYMFONY_VERSION} \
            symfony/http-kernel:${SYMFONY_VERSION} \
            --no-update --no-scripts
    - |
        composer require \
            symfony/console:${SYMFONY_VERSION} \
            symfony/twig-bundle:${SYMFONY_VERSION} \
            --no-update --no-scripts
    - composer update --prefer-dist
    - (cd src/Component && composer update --prefer-dist)

script:
    - composer validate --strict
    - (cd src/Component && composer validate --strict)

    - composer analyse

    - vendor/bin/phpspec run
    - (cd src/Component && vendor/bin/phpspec run)

    - vendor/bin/phpunit
